/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import React, { useContext } from "react";
import DesktopMenu from "./DesktopMenu";
import styles from "../../styles/Home.module.scss";
import Image from "next/image";
import { Popbutton } from "./Popbutton";
import { SettingContext } from "../context/SettingContext";
import { useWindowSize } from "../hook/useWindowSize";
import { MobileMenu } from "./MobileMenu";

interface Props {
  title?: string;
}

export default function Layout(props: React.PropsWithChildren<Props>) {
  const { setting } = useContext(SettingContext);
  const { innerWidth } = useWindowSize();
  return (
    <div
      style={{
        overflow: "auto",
        height: window.innerHeight,
        scrollBehavior: "smooth",
      }}
      id="main"
    >
      <Head>
        <title>{props.title ? props.title : "AKASHA"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>
        <img
          src="https://firebasestorage.googleapis.com/v0/b/akasharift-860aa.appspot.com/o/akasha_rift%2FAR_0_Curtain.png?alt=media&token=b3a36bfc-9671-4feb-af81-8d2f89b866b1"
          alt=""
          style={{
            position: "fixed",
            width: "100%",
            objectFit: "fill",
            height: "150%",
            zIndex: -1,
          }}
        />
      </div> */}
      {innerWidth > 1000 ? <DesktopMenu /> : <MobileMenu />}
      <div className="content">{props.children}</div>
      {/* <footer className={styles.footer}>
        <div>
          <a href="#" target="_blank" rel="noopener noreferrer">
            Under Construction
          </a>
          {!setting.loading && (
            <p
              style={{
                width: "55%",
                color: "#f3f3f3",
                margin: "auto",
                marginTop: "0.2rem",
                textAlign: "center",
              }}
              dangerouslySetInnerHTML={{
                __html: setting.value.footer.content + "",
              }}
            ></p>
          )}
        </div>
      </footer> */}
      <Popbutton />
    </div>
  );
}
